# Generated by Django 4.1 on 2022-10-15 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelLibro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('autor', models.CharField(max_length=60)),
                ('genero', models.CharField(choices=[('Ciencia ficción', 'Ciencia ficción'), ('Fantasía', 'Fantasía'), ('Aventura', 'Aventura'), ('Policial', 'Policial'), ('Novela histórica', 'Novela histórica'), ('Cuento', 'Cuento'), ('Obra de teatro', 'Obra de teatro'), ('Poesía', 'Poesía'), ('Misterio', 'Misterio'), ('Horror', 'Horror')], max_length=60)),
                ('idioma', models.CharField(max_length=20)),
                ('precio', models.FloatField()),
                ('portada', models.ImageField(upload_to='portadas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='avatares')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
